.travis.yml
package.json

Fix(NPM): Setup semantic release

---

CODE_OF_CONDUCT.md

Create Code Of Conduct

---

README.md
lib/morphism.js
package-lock.json
test/morphism.spec.js

Fix(Docs): Update global documentation. Bugs fixes

---

package.json

fix: Update semantic-release npm script

---

README.md
package.json
src/morphism.ts
tsconfig.json

Non Gzipped
**Before** 
**After**

Feat: Remove Lodash

---

.circleci/config.yml
README.md
now.json
package-lock.json
package.json
src/morphism.ts

feat: Automate Doc generation and Deployment on Zeit

---

package-lock.json
src/helpers.ts
src/jsObjects.spec.ts
src/morphism.spec.ts
src/morphism.ts
src/typings.spec.ts

Allows to infer the type of the target from the structure of the schema. Depending on how the currying function is used, it will output the right artifact (Mapper, Typed Results).

Feat: Infer Target Type from Schema

---

.circleci/config.yml

fix: Remove cache management on dist folder

---

README.md
src/classObjects.spec.ts
src/jsObjects.spec.ts
src/morphism.ts
tsconfig.json

- Add `toJSObject`, `toClassObject`, `morph` decorators

Feat: Add Function decorators

---

README.md

fix: update readme badges

---

src/morphism.ts
src/typescript.spec.ts

fix(types): allow to supply destination and source type on morphism()

---

README.md

fix: add missing doc

---

src/morphism.ts
src/typescript.spec.ts

fix: allow partial completion for currying function

---

package.json

fix: update package.json keywords

---

src/MorphismTree.ts
src/helpers.ts
src/morphism.spec.ts
src/morphism.ts
src/types.ts

Feat: Add createSchema and allow to strip undefined values on target

---

src/morphism.ts
src/typescript.spec.ts

fix: circular source type. improve typings

---

package-lock.json
package.json

Greenkeeper/now 15.6.2

---

src/morphism.ts

feat: export validation artifacts

---

src/morphism.spec.ts
src/morphism.ts

fix: expose Validation object instead of Validation interface

---

src/morphism.spec.ts
src/morphism.ts

fix: expose ValidationError class

---

src/morphism.spec.ts
src/morphism.ts
src/validation/Validation.spec.ts

fix: expose ValidatorError instead of ValidationError
